apiVersion: v1
kind: Secret
metadata:
  name: laura-app-stg-secret
  namespace: argocd
  labels:
    "argocd.argoproj.io/secret-type": "cluster"
type: Opaque
stringData:
  config: |
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:36485
  name: kind-argocd-hub
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:40563
  name: kind-capi-test
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:37209
  name: kind-certchecker
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:43859
  name: kind-laura-app-prod
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:33641
  name: kind-laura-app-stg
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:39711
  name: talos-default
contexts:
- context:
    cluster: talos-default
    namespace: default
    user: admin@talos-default
  name: admin@talos-default
- context:
    cluster: kind-argocd-hub
    user: kind-argocd-hub
  name: kind-argocd-hub
- context:
    cluster: kind-capi-test
    user: kind-capi-test
  name: kind-capi-test
- context:
    cluster: kind-certchecker
    user: kind-certchecker
  name: kind-certchecker
- context:
    cluster: kind-laura-app-prod
    user: kind-laura-app-prod
  name: kind-laura-app-prod
- context:
    cluster: kind-laura-app-stg
    user: kind-laura-app-stg
  name: kind-laura-app-stg
current-context: kind-argocd-hub
kind: Config
preferences: {}
users:
- name: admin@talos-default
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
- name: kind-argocd-hub
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
- name: kind-capi-test
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
- name: kind-certchecker
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
- name: kind-laura-app-prod
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
- name: kind-laura-app-stg
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED

